version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
      - image: circleci/mysql:5.7.22
    steps:
      - checkout
      - run: bundle install
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rails test
  deploy:
      machine:
          image: circleci/classic:edge
      steps:
        - run:
            name: "authorize-security-group-ingress"
            command: |
              IP=`curl -s ifconfig.me`
              echo "#!/bin/bash" > ./sg.sh
              echo "aws configure set region ap-northeast-1" >> ./sg.sh
              echo "aws ec2 authorize-security-group-ingress --group-id sg-0956ebc079e18ba40 --protocol tcp --port 22 --cidr ${IP}/32" >> ./sg.sh
              bash ./sg.sh
        - add_ssh_keys:
        - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/rails/anima && git pull'
        - run:
            name: "revoke-security-group-ingress"
            command: |
              IP=`curl -s ifconfig.me`
              echo "#!/bin/bash" > ./sg.sh
              echo "aws configure set region ap-northeast-1" >> ./sg.sh
              echo "aws ec2 revoke-security-group-ingress --group-id sg-0956ebc079e18ba40 --protocol tcp --port 22 --cidr ${IP}/32" >> ./sg.sh
              bash ./sg.sh
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                  branches:
                        only: master
                    
                        