version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
      - image: circleci/mysql:5.7.22
    steps:
      - checkout
      - run: bundle install
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rails test
    deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            - add_ssh_keys:
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/rails/anima&& git pull'