version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0-node-browsers
      - image: circleci/mysql:5.7.22
    steps:
      - checkout
      - run: bundle install
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rails test

      deploy:
        machine:
            image: circleci/classic:edge
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            # CircleCI に登録した環境変数を使って SSH
            - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/rails/anima && git pull'
            
 workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                # master ブランチに push された場合のみ deploy
                filters:
                    branches:
                        only: master